"""Update product models

Revision ID: 402ffb0f3570
Revises: ed2cc0e59902
Create Date: 2024-12-06 01:49:42.226885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '402ffb0f3570'
down_revision = 'ed2cc0e59902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_details', schema=None) as batch_op:
        batch_op.drop_index('computer_id')
        batch_op.drop_index('laminator_id')
        batch_op.drop_index('laptop_id')
        batch_op.drop_index('monitor_id')
        batch_op.drop_index('photocopier_id')
        batch_op.drop_index('printer_id')
        batch_op.drop_index('projector_id')
        batch_op.drop_index('scanner_id')
        batch_op.drop_index('whiteboard_id')

    op.drop_table('product_details')
    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('laminators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('photocopiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('projectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('scanners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('whiteboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboards', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('scanners', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('projectors', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('photocopiers', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('laminators', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.drop_column('details')

    op.create_table('product_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('offer', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('computer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('printer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projector_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photocopier_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('laminator_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('whiteboard_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monitor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('laptop_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scanner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], name='product_details_ibfk_1'),
    sa.ForeignKeyConstraint(['laminator_id'], ['laminators.id'], name='product_details_ibfk_5'),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], name='product_details_ibfk_8'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name='product_details_ibfk_7'),
    sa.ForeignKeyConstraint(['photocopier_id'], ['photocopiers.id'], name='product_details_ibfk_4'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], name='product_details_ibfk_2'),
    sa.ForeignKeyConstraint(['projector_id'], ['projectors.id'], name='product_details_ibfk_3'),
    sa.ForeignKeyConstraint(['scanner_id'], ['scanners.id'], name='product_details_ibfk_9'),
    sa.ForeignKeyConstraint(['whiteboard_id'], ['whiteboards.id'], name='product_details_ibfk_6'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product_details', schema=None) as batch_op:
        batch_op.create_index('whiteboard_id', ['whiteboard_id'], unique=True)
        batch_op.create_index('scanner_id', ['scanner_id'], unique=True)
        batch_op.create_index('projector_id', ['projector_id'], unique=True)
        batch_op.create_index('printer_id', ['printer_id'], unique=True)
        batch_op.create_index('photocopier_id', ['photocopier_id'], unique=True)
        batch_op.create_index('monitor_id', ['monitor_id'], unique=True)
        batch_op.create_index('laptop_id', ['laptop_id'], unique=True)
        batch_op.create_index('laminator_id', ['laminator_id'], unique=True)
        batch_op.create_index('computer_id', ['computer_id'], unique=True)

    # ### end Alembic commands ###
