"""Added new changes to models

Revision ID: 4c423b03a84b
Revises: 
Create Date: 2025-01-08 23:04:33.897513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c423b03a84b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('storage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_entered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('pin_entered')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('size')
        batch_op.drop_column('storage')
        batch_op.drop_column('ram')
        batch_op.drop_column('type')
        batch_op.drop_column('details')

    # ### end Alembic commands ###
