"""Recreate missing table

Revision ID: 67d891e2107d
Revises: 402ffb0f3570
Create Date: 2024-12-06 02:30:31.203929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d891e2107d'
down_revision = '402ffb0f3570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('laminators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('photocopiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('projectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('scanners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('whiteboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboards', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('scanners', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('projectors', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('photocopiers', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('laminators', schema=None) as batch_op:
        batch_op.drop_column('details')

    with op.batch_alter_table('computers', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
