"""Add particular column to TransactionProduct

Revision ID: 729d60d641f8
Revises: f5399f9f8af7
Create Date: 2024-09-09 16:00:44.709149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '729d60d641f8'
down_revision = 'f5399f9f8af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=200),
               nullable=False)

    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('particular', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_transaction_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_products_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_products_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_products_product_id'))
        batch_op.drop_column('particular')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=1000),
               nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_product_id'))

    # ### end Alembic commands ###
