"""Add type, ram, storage, size, and brand to Product model

Revision ID: 7b9427066679
Revises: 67d891e2107d
Create Date: 2024-12-06 19:40:11.606101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9427066679'
down_revision = '67d891e2107d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('storage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('size')
        batch_op.drop_column('storage')
        batch_op.drop_column('ram')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
