"""Add Computer model

Revision ID: 7e88fc3ccf6c
Revises: 729d60d641f8
Create Date: 2024-10-21 18:44:20.986669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e88fc3ccf6c'
down_revision = '729d60d641f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('computer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'computers', ['computer_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('computer_id')

    # ### end Alembic commands ###
