"""Update product model

Revision ID: 8fec250e0f88
Revises: 303eb62d6c0b
Create Date: 2024-09-03 04:20:52.669098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fec250e0f88'
down_revision = '303eb62d6c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('response_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('response_description')
        batch_op.drop_column('response_code')

    # ### end Alembic commands ###
