"""Add printer relationship to order items

Revision ID: a041b1e10813
Revises: 7e88fc3ccf6c
Create Date: 2024-10-22 11:43:25.034596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a041b1e10813'
down_revision = '7e88fc3ccf6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('computer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('printer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'printers', ['printer_id'], ['id'])
        batch_op.create_foreign_key(None, 'computers', ['computer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('printer_id')
        batch_op.drop_column('computer_id')

    # ### end Alembic commands ###
