"""Change image_path column type to String

Revision ID: c560ffc5bb99
Revises: 
Create Date: 2024-09-02 14:03:01.391353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c560ffc5bb99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('products')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_claimed')
        batch_op.drop_index('name')

    op.drop_table('items')
    op.drop_table('hotitem')
    with op.batch_alter_table('product_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.alter_column('Status',
               existing_type=mysql.ENUM('Pending', 'Processed', 'Rejected'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('Reason',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.alter_column('Reason',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('Status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Pending', 'Processed', 'Rejected'),
               existing_nullable=True)

    with op.batch_alter_table('product_payment', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    op.create_table('hotitem',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('interval', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('claimed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('interval', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('claimed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('ix_items_claimed', ['claimed'], unique=False)

    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    # ### end Alembic commands ###
