"""Add more products

Revision ID: ed2cc0e59902
Revises: 3b0edc6d6ed0
Create Date: 2024-10-22 12:50:39.388089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2cc0e59902'
down_revision = '3b0edc6d6ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('projector_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photocopier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('laminator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('whiteboard_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('laptop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'scanners', ['scanner_id'], ['id'])
        batch_op.create_foreign_key(None, 'whiteboards', ['whiteboard_id'], ['id'])
        batch_op.create_foreign_key(None, 'projectors', ['projector_id'], ['id'])
        batch_op.create_foreign_key(None, 'laptops', ['laptop_id'], ['id'])
        batch_op.create_foreign_key(None, 'laminators', ['laminator_id'], ['id'])
        batch_op.create_foreign_key(None, 'monitors', ['monitor_id'], ['id'])
        batch_op.create_foreign_key(None, 'photocopiers', ['photocopier_id'], ['id'])

    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('projector_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photocopier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('laminator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('whiteboard_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('laptop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'scanners', ['scanner_id'], ['id'])
        batch_op.create_foreign_key(None, 'monitors', ['monitor_id'], ['id'])
        batch_op.create_foreign_key(None, 'laminators', ['laminator_id'], ['id'])
        batch_op.create_foreign_key(None, 'whiteboards', ['whiteboard_id'], ['id'])
        batch_op.create_foreign_key(None, 'projectors', ['projector_id'], ['id'])
        batch_op.create_foreign_key(None, 'photocopiers', ['photocopier_id'], ['id'])
        batch_op.create_foreign_key(None, 'laptops', ['laptop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('laptop_id')
        batch_op.drop_column('monitor_id')
        batch_op.drop_column('whiteboard_id')
        batch_op.drop_column('laminator_id')
        batch_op.drop_column('photocopier_id')
        batch_op.drop_column('projector_id')
        batch_op.drop_column('scanner_id')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('laptop_id')
        batch_op.drop_column('monitor_id')
        batch_op.drop_column('whiteboard_id')
        batch_op.drop_column('laminator_id')
        batch_op.drop_column('photocopier_id')
        batch_op.drop_column('projector_id')
        batch_op.drop_column('scanner_id')

    # ### end Alembic commands ###
