"""adding quantities tracking to table

Revision ID: f5399f9f8af7
Revises: 179b2dd6bbaa
Create Date: 2024-09-03 15:15:58.166785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5399f9f8af7'
down_revision = '179b2dd6bbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=1000),
               nullable=True)
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
